# Configurations
title:            Table of Contents
longtitle:        Table of Contents
author:           Simeon Wuthier
email:            mail@simewu.com
description: >
  Read O-RAN Alliance specifications in a GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://simewu.github.io'
baseurl:          '/spec-reader'
rss:              RSS
download_url:     'https://github.com/Simewu/spec-reader/raw/refs/heads/main/documents'
github_page_url:  'https://github.com/Simewu/spec-reader/blob/main/pages'

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.svg

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - README.md
  - documents
  - pages
  - vendor
  - assets/oran_specifications_combined.md

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
